### ISSUE TITLE
Unexpected token when i am running ember server

### ISSUE THREAD

**Issue by emiliogambone** [Matt-Jensen/ember-cli-g-maps#98]
I just installed ember-cli-g-maps, and when i'm trying to set up the server i have this error:

Unexpected token .
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Project.require (/home/emilio/vigifarmaco-mobile/node_modules/ember-cli/lib/models/project.js:322:14)
    at Project.config (/home/emilio/vigifarmaco-mobile/node_modules/ember-cli/lib/models/project.js:209:28)
    at Class.init (/home/emilio/vigifarmaco-mobile/node_modules/ember-local-storage/index.js:54:38)

**Comment by emiliogambone** [comment]
any idea?

**Comment by Matt-Jensen** [comment]
@emiliogambone can you create an example repo or twiddle for me?
